### PR TITLE
fix(form): properly register the submit attribute

### LINKED ISSUE #247: ui-form: strange build issue
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Docker image: node) | Windows 10 (with WSL)

* **Node Version:**
13.10.0

* **NPM Version:**
6.4.13

* **Webpack**
webpack 4.42.1

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**

Using the latest base project generated by `aurelia-cli` (with small twinkering in the webapp config, mainly to change a little how style files are loaded), when I'm building my app, it's working great if I'm in dev env (using `npm run build:dev`).

But if I build it in production environment (using `npm run build`) and serve it directly (`http-server dist`), I get the following error in my console: `Error: Unable to find module with ID: @aurelia-ux/form.html` (I noticed immediately that it seems to miss a `form/` folder in the module name).

I activated the debug log in production to get more details and here is what I see:
```
DEBUG [aurelia] Loading plugin aurelia-templating-binding. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin aurelia-templating-binding. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin aurelia-templating-resources. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin aurelia-templating-resources. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin aurelia-event-aggregator. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin aurelia-event-aggregator. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin aurelia-history-browser. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin aurelia-history-browser. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin aurelia-templating-router. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin aurelia-templating-router. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/button. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/button. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/card. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/card. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/checkbox. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/checkbox. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/core. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/core. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/form. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/form. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/input. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/input. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/list. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/list. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/icons. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/icons. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/grid. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/grid. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/select. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/select. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin @aurelia-ux/textarea. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin @aurelia-ux/textarea. aurelia-logging-console.js:15:31
DEBUG [aurelia] Loading plugin resources/index. aurelia-logging-console.js:15:31
DEBUG [aurelia] Configured plugin resources/index. aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/button/ux-button.html 
Array [ "@aurelia-ux/core/effects/paper-ripple.css", "@aurelia-ux/button/ux-button.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/card/ux-card.html 
Array [ "@aurelia-ux/card/ux-card.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/card/ux-card-header.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/card/ux-card-action-row.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/card/ux-card-content.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/card/ux-card-footer.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/card/ux-card-separator.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/checkbox/ux-checkbox.html 
Array [ "@aurelia-ux/core/effects/paper-ripple.css", "@aurelia-ux/checkbox/ux-checkbox.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/form/ux-form.html 
Array [ "@aurelia-ux/form/ux-form.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/form/ux-field.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/input/ux-input.html 
Array [ "@aurelia-ux/input/ux-input.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/list/ux-list.html 
Array [ "@aurelia-ux/list/ux-list.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/list/ux-list-item.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/icons/ux-icon.html 
Array [ "@aurelia-ux/icons/ux-icon.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/grid/ux-grid.html 
Array [ "@aurelia-ux/grid/ux-grid.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/grid/ux-grid-cell.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/select/ux-select.html 
Array [ "@aurelia-ux/core/effects/paper-ripple.css", "@aurelia-ux/select/ux-select.css" ]
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/select/ux-optgroup.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/select/ux-option.html 
Array []
aurelia-logging-console.js:15:31
DEBUG [templating] importing resources for @aurelia-ux/textarea/ux-textarea.html 
Array [ "@aurelia-ux/textarea/ux-textarea.css" ]
aurelia-logging-console.js:15:31
onmozfullscreenchange est obsolète. aurelia-metadata.js:65:24
onmozfullscreenerror est obsolète. aurelia-metadata.js:65:24
Error: Unable to find module with ID: @aurelia-ux/form.html aurelia-loader-webpack.js:197:34
```

I don't find the debug helping there. We don't know why this module was required. Even more disturbing is the fact that `@aurelia-ux/form/ux-form.html` seems to have been loaded properly before the bug happens.

**Expected/desired behavior:**

The app should work the same way whatever env we use for building it.

My app is currently open source, so if you want to check it out, here it is: https://heptapod.lsystems.fr/qraynaud/recipe-calculator

### PR DESCRIPTION
**Pull request by ben-girardet**
Fixes #247

### CODE REVIEW

File: packages/form/src/index.ts [hunk 1]
```diff
@@ -10,6 +10,6 @@ export function configure(config: FrameworkConfiguration) {
   config.globalResources([
     PLATFORM.moduleName('./ux-form'),
     PLATFORM.moduleName('./ux-field'),
-    UxSubmitCustomAttribute
+    PLATFORM.moduleName('./ux-submit-attribute'),
```
Comment (bigopon) [inline packages/form/src/index.ts]: we need either this or `@customAttribute..` only. I think the decorator should be preferred, as it can help with optimization

Comment (ben-girardet) [reply packages/form/src/index.ts]: So what you mean is that we should have one OR the other but not BOTH ?

Comment (bigopon) [reply packages/form/src/index.ts]: Yes, having one is enough. Having 2 is the same. Just the downside of `PLATFORM.moduleName` is it disable some optimization of webpack on the module referred

Comment (ben-girardet) [reply packages/form/src/index.ts]: What about `@customElement` ? Should we also not use `PLATFORM.moduleName()` when there is an explicit decorator on the custom element ?

Comment (bigopon) [reply packages/form/src/index.ts]: no, we don't have to, but it's good to be explicit. `PLATFORM.moduleName` does a few things:
- deoptimize a module, to keep the names of its exported members kept as is
- signal webpack to register a module as dependency of current module

Comment (ben-girardet) [reply packages/form/src/index.ts]: Yeah, I've learnt with the Aurelia team that we aim to be as explicit as possible. This is great.

The most explicit is the usage of `@customAttribute()` and `@customElement()` right ?

So, for the `@customAttribute` you say that we _should not_ use PLATFORM.moduleName().

Just want to clarify to make sure I get it right for the future... Regarding `@customElement`. _Should we use_ PLATFORM.moduleName() or _should we not_ (and benefit from better module optimization) ?

**Comment by ben-girardet** [comment]
@bigopon thanks for your comments. I've updated the PR.

File: packages/form/src/index.ts (hunk 1 above)
Comment (bigopon) [reply packages/form/src/index.ts]: For custom element. ModuleName is needed because we need to inform webpack that it needs to bundle the corresponding view too, beside "do not rename export" signal

File: packages/form/src/ux-submit-attribute.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
-import { inject } from 'aurelia-dependency-injection';
+import { inject, customAttribute } from 'aurelia-framework';
```
Comment (bigopon) [inline packages/form/src/ux-submit-attribute.ts]: I think we better take dependency on the core module instead of this module. It would be custom attribute from aurelia templating.

Comment (ben-girardet) [reply packages/form/src/ux-submit-attribute.ts]: fixed with https://github.com/aurelia/ux/pull/248/commits/91d7d344f65405a626f9c98cc6346059d0d407c8

**Comment by ben-girardet** [comment]
Ready for next review / merge @bigopon

**Comment by bigopon** [comment]
Thanks @ben-girardet

**Comment by bigopon** [comment]
@EisenbergEffect pinging you to queue for a release

**Comment by EisenbergEffect** [comment]
Adding it to the list. Do we want to release now or wait for the other couple of fixes that are in progress?

**Comment by bigopon** [comment]
@EisenbergEffect it seems there're 2 more small PRs that could go with this. Let's wait for @ben-girardet to resolve all comments in those. If it's taking more than today than we can just go for this first
